<a href="https://colab.research.google.com/github/PozzOver13/learning/blob/main/stats_and_probability/20240206_markov_chains.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# References

https://elijahpotter.dev/articles/markov_chains_are_the_original_language_models?utm_source=substack&utm_medium=email  Markov Chains to predict next word  
https://www.datacamp.com/tutorial/markov-chains-python-tutorial  Markov Chains in python  
https://en.wikipedia.org/wiki/Markov_chain Markov Chain  
https://setosa.io/ev/markov-chains/  Markov Chains Explained  
https://www.youtube.com/watch?v=i3AkTO9HLXo&list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV Markov Chains Clearly Explained! Part - 1  
https://www.youtube.com/watch?v=SS_pqgFziAg  Chris Fonnesbeck: Un'introduzione a Markov Chain Monte Carlo utilizzando PyMC3 | PyData Londra 2019  
https://arxiv.org/ftp/arxiv/papers/1106/1106.4513.pdf  A Markov Chain approach to determine the optimal performance period and bad definition for credit scorecard  
https://www.youtube.com/watch?v=sAqhzUBlYY4 Markov chains and the credit rating migration matrix

# Markov Chains

Markov Chains are mathematical models that represent a sequence of events where the probability of transitioning from one state to another depends solely on the current state and is independent of the sequence of events that preceded it. In other words, the future state of the system is determined only by its present state, and not by how it arrived at that state.

In the context of credit risk for a data scientist, Markov Chains can be used to model the transitions between different credit states of a customer over time. Each state represents a certain creditworthiness level, such as good, fair, or poor credit. The transitions between these states are governed by transition probabilities, which are the probabilities of moving from one credit state to another in a given time period.

For example, consider a simplified Markov Chain representing credit states {Good, Fair, Poor}. The transition matrix might look like:

```
|   0.9   0.1   0     |   Good
|   0.2   0.7   0.1   |   Fair
|   0     0.3   0.7   |   Poor
```

Here, the numbers in the matrix represent transition probabilities. If a customer is currently in a "Good" credit state, there's a 90% chance they will remain in the "Good" state, a 10% chance they will move to the "Fair" state, and no chance of moving to the "Poor" state in the next time period.

By simulating the Markov Chain over multiple time periods, a data scientist in credit risk can model the dynamics of credit transitions and assess the likelihood of a customer moving between credit states. This information can be valuable for predicting creditworthiness changes and managing associated risks in a financial portfolio.

# Alice next location example

In [28]:
import numpy as np
import pandas as pd

In [29]:
end_prob_start_from_grocery = [0.3, 0.7] # 70% of leaving for the planetarium every hour starting from the grocery store
end_prob_start_from_planetarium = [0.1, 0.9] # 70% of staying at the planetarium every hour starting from the planetarium

In [30]:
matrix_location_prob = np.column_stack((end_prob_start_from_grocery, end_prob_start_from_planetarium))

In [31]:
matrix_location_prob

array([[0.3, 0.1],
       [0.7, 0.9]])

In [32]:
pd.DataFrame(matrix_location_prob,
             columns=['start_at_grocery', 'start_at_planetarium'],
             index=['end_at_grocery', 'end_at_planetarium'])

start_at_grocery  start_at_planetarium
end_at_grocery                   0.3                   0.1
end_at_planetarium               0.7                   0.9

In [33]:
presence_prob = [0.25, 0.75]

In [34]:
matrix_actual_presence_prob = np.array(presence_prob)

In [35]:
matrix_actual_presence_prob.reshape(2, 1)

array([[0.25],
       [0.75]])

In [36]:
pd.DataFrame(matrix_actual_presence_prob.reshape(2, 1),
             columns=['% Alice Present'],
             index=['grocery', 'planetarium'])

% Alice Present
grocery                 0.25
planetarium             0.75

## Next hour probabilities

In [37]:
next_hour_prob = np.dot(matrix_location_prob, matrix_actual_presence_prob)
next_hour_prob

array([0.15, 0.85])

In [38]:
pd.DataFrame(next_hour_prob.reshape(2, 1),
             columns=['% Alice Present'],
             index=['grocery', 'planetarium'])

% Alice Present
grocery                 0.15
planetarium             0.85

## Next 2 hours probabilities

In [39]:
next_2_hours_prob = np.dot(np.dot(matrix_location_prob, matrix_location_prob), matrix_actual_presence_prob)
next_2_hours_prob

array([0.13, 0.87])

In [40]:
pd.DataFrame(next_2_hours_prob.reshape(2, 1),
             columns=['% Alice Present'],
             index=['grocery', 'planetarium'])

% Alice Present
grocery                 0.13
planetarium             0.87

# Next 10 hours probabilities

In [45]:
steps=11
print("starting stationary state:")
print(matrix_actual_presence_prob)
print("markov chains evolution:")
for i in np.arange(steps):
  # print(i)
  if i == 0:
    transition_matrix = matrix_location_prob
  else:
    transition_matrix = np.dot(transition_matrix, matrix_location_prob)

  s = np.dot(transition_matrix, matrix_actual_presence_prob)
  # print(s)
print(f"ending stationary state after {i} steps:")
print(s)
print("using matrix power:")
transition_matrix = np.linalg.matrix_power(matrix_location_prob, steps)
s = np.dot(transition_matrix, matrix_actual_presence_prob)
print(s)

starting stationary state:
[0.25 0.75]
markov chains evolution:
ending stationary state after 10 steps:
[0.125 0.875]
using matrix power:
[0.125 0.875]


# Datacamp tutorial

- A Markov chain is a mathematical system usually defined as a collection of random variables, that transition from one state to another according to certain probabilistic rules. These set of transition satisfies the **Markov Property**, which states that the probability of transitioning to any particular state is dependent solely on the current state and time elapsed, and not on the sequence of state that preceded it. This unique characteristic of Markov processes render them **memoryless**.
- They are widely employed in economics, game theory, communication theory, genetics and finance.
- They arise broadly in statistical specially Bayesian statistics and information-theoretical contexts.
- The algorithm known as PageRank, which was originally proposed for the internet search engine Google, is based on a Markov process.
- A Markov chain is a random process with the Markov property. A random process or often called stochastic property is a mathematical object defined as a collection of random variables. A Markov chain has either discrete state space (set of possible values of the random variables) or discrete index set (often representing time) - given the fact, many variations for a Markov chain exists. Usually the term "Markov chain" is reserved for a process with a discrete set of times, that is a Discrete Time Markov chain (DTMC).
- Markov property, such that the probability of moving to the next state depends only on the present state and not on the previous states.
- The probabilities associated with various state changes are called transition probabilities.